app:
  name: Product-Service
  httpProt: 0.0.0.0:12644
  grpcProt: 0.0.0.0:12645

mongoDb:
  uri: 

postgresDb:
  uri: postgresql://postgres:root@localhost:5432/product?sslmode=disable&TimeZone=Asia/Bangkok

redis:
  uri: redis://localhost:6379
